#!/bin/sh

# Code to Pull the current branch
# Author: @fazenecture
# git p

# Color Variables
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
orange='\033[33m'
# clear the color
clear='\033[0m'

currentBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$currentBranch" ]
then
    if git pull;
    then
        echo "✅ ${green}Pulled All The Latest Changes from ${currentBranch}${clear}"
    else
        echo "🚫 ${red}Error Pulling the Changes${clear}"  
    fi
else
    echo "${red}🚫 Error: You are not in a branch${clear}"
    exit 1
fi

       

